name: ni-health-accessibility
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - matplotlib
  - folium
  - numpy
  - rasterio
  - rasterstats
  - scikit-image
  - osmnx
  - openpyxl
  - jupyterlab
